language: cpp

before_install:
  - sudo apt-get update  -qq
  - sudo apt-get install -qq valgrind

script:
  - g++ -v
  - g++ macro_check.cpp -o macro_check
  - ./macro_check
  - valgrind ./macro_check
